petstagram/accounts/urls.py
from django.urls import path, include

import petstagram
from petstagram.accounts import views
urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('profile/<int:pk>/', include([
        path('', views.profile_details, name='profile_details'),
        path('edit/', views.profile_edit, name='profile_edit'),
        path('delete/', views.profile_delete, name='profile_delete'),
    ]))
]

petstagram/common/urls.py
from petstagram.common import views
from django.urls import path

urlpatterns = [
    path('', views.home_page, name='home'),
]

petstagram/pets/urls.py
from django.urls import path, include

from petstagram.pets import views

urlpatterns = [
    path('add/', views.pet_add_page, name='add-pet'),
    path('<str:username>/pet/<slug:pet_slug>/', include([
        path('', views.pet_details_page, name='pet-details'),
        path('edit/', views.pet_edit_page, name='pet-edit'),
        path('delete/', views.pet_delete_page, name='pet-delete'),
    ])),
]

petstagram/photos/urls.py
from django.urls import path, include
from petstagram.photos import views

urlpatterns = [
    path('add/', views.photo_add_page, name='photo-add'),
    path('<int:pk>', include([
        path('', views.photo_details_page, name='photo-details'),
        path('edit/', views.photo_edit_page, name='photo-edit'),
        ])),
]

petstagram/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram.common.urls')),
    path('accounts/', include('petstagram.accounts.urls')),
    path('pets/', include('petstagram.pets.urls')),
    path('photos/', include('petstagram.photos.urls'))
]

petstagram/accounts/models.py
from django.db import models

# Create your models here.

petstagram/common/models.py
from django.db import models

from petstagram.photos.models import Photo


class Comment(models.Model):
    text = models.TextField(
        max_length=300,
    )

    date_time_of_publication = models.DateTimeField(
        auto_now_add=True,
    )

    to_photo = models.ForeignKey(
        to=Photo,
        on_delete=models.CASCADE,
    )

class Like(models.Model):
    to_photo = models.ForeignKey(
        to=Photo,
        on_delete=models.CASCADE,
    )

petstagram/pets/models.py
from django.db import models
from django.utils.text import slugify


class Pet(models.Model):
    name = models.CharField(max_length=30)

    personal_photo = models.URLField()

    date_of_birth = models.DateField(
        blank=True, null=True
    )



    slug = models.SlugField(
        null=True, blank=True, unique=True, editable=False
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if not self.slug:
            self.slug = slugify(f'{self.name}-{self.id}')

        super().save(*args, **kwargs)


    def __str__(self):
        return self.name

petstagram/photos/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from petstagram.pets.models import Pet
from petstagram.photos.validators import FileSizeValidator


class Photo(models.Model):
    photo = models.ImageField(
        upload_to='mediafiles',
        validators=[
            FileSizeValidator(5)
        ],
    )

    description = models.TextField(
        max_length=300,
        validators=(
            MinLengthValidator(10),
        ),
        blank=True,
        null=True,
    )

    location = models.CharField(
        max_length=30,
        blank=True,
        null=True,
    )

    tagged_pets = models.ManyToManyField(
        to=Pet,
        blank=True,
    )

    date_of_publication = models.DateField(
        auto_now_add=True,
    )

petstagram/accounts/views.py
from django.shortcuts import render


def login(request):
    return render(request, 'accounts/login-page.html')

def register(request):
    return render(request, 'accounts/register-page.html')

def profile_delete(request, pk):
    return render(request, 'accounts/profile-delete-page.html')

def profile_details(request, pk):
    return render(request, 'accounts/profile-details-page.html')

def profile_edit(request, pk):
    return render(request, 'accounts/profile-edit-page.html')

petstagram/common/views.py
from django.shortcuts import render

def home_page(request):
    return render(request, 'common/home-page.html')

petstagram/pets/views.py
from django.shortcuts import render

def pet_add_page(request):
    return render(request, 'pets/pet-add-page.html')

def pet_edit_page(request, username: str, pet_slug: str):
    return render(request, 'pets/pet-edit-page.html')

def pet_details_page(request, username: str, pet_slug: str):
    return render(request, 'pets/pet-details-page.html')

def pet_delete_page(request, username: str, pet_slug: str):
    return render(request, 'pets/pet-delete-page.html')

petstagram/photos/views.py
from django.shortcuts import render

def photo_add_page(request):
    return render(request, 'photos/photo-add-page.html')

def photo_edit_page(request, pk: int):
    return render(request, 'photos/photo-edit-page.html')

def photo_details_page(request, pk: int):
    return render(request, 'photos/photo-details-page.html')

templates/accounts/login-page.html
pyt<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet" href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/static/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">

                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Login Page -->
                        <a href="#">
                            <i>Login</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Register Page -->
                        <a href="">
                            <i>Register</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>

    <!-- Start Login Section-->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Login Form-->
            <form action="#">
                <p>
                    <label for="id_username">Username:</label>
                    <input type="text" placeholder="Username">
                </p>
                <p>
                    <label for="id_password">Password:</label>
                    <input type="password" placeholder="Password">
                </p>

                <!-- Login Button-->
                <button type="submit">Log in</button>
            </form>
            <!-- End Login Form -->

        </div>
        <div class="second-option">

            <!-- Link to Register Page-->
            <p>Don't have an account? <a href="#">Register</a></p>
        </div>
    </div>
    <!-- End Login Section-->

</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2024 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

templates/accounts/profile-delete-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet" href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/static/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">
                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <!-- Log out -->
                        <a href="#">
                            <i>Log out</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>

    <!-- Start Delete Profile Section -->
        <div class="delete-profile">
            <h1>
                Are you sure you want to delete your profile?
            </h1>
            <div class="sure-buttons">
                <!-- Yes (Delete Profile) Button -->
                <button>Yes</button>
                <!-- Go Back Button -->
                <a class="edit-btn" href="javascript:history.back()">Go Back</a>
            </div>
            <img src="/static/images/are_you_sure_cat.gif" alt="are you sure cat git">
        </div>
    <!-- End Delete Profile Section -->

</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2024 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

templates/accounts/profile-details-page.html
<!DOCTYPE html>
<html lang="en">
  <!-- Starts Head Section -->
  <head>
    <link rel="stylesheet" href="/static/css/styles.css" />
    <link
      rel="icon"
      type="image/x-icon"
      href="/static/images/free-30-instagram-stories-icons23_122570.png"
    />
    <title>Petstagram</title>
  </head>
  <!-- End Head Section -->

  <!-- Starts Body Section -->
  <body>
    <!-- Starts Header Section with Navigation Bar -->
    <header>
      <nav class="navbar">
        <div class="container">
          <div class="logo">
            <!-- Link to Home Page -->
            <a href="#">
              <img
                width="50px"
                src="/static/images/free-30-instagram-stories-icons23_122570.png"
                alt="img1"
              />
            </a>

            <!-- Link to Home Page -->
            <a class="home" href="#">
              <i>Petstagram</i>
            </a>
          </div>

          <div class="nav-links">
            <ul class="nav-group">
              <li class="nav-item">
                <!-- Link to Add Pet Page -->
                <a href="#">
                  <i>Add Pet</i>
                </a>
              </li>
              <li class="nav-item">
                <!-- Link to Add Photo Page -->
                <a href="#">
                  <i>Add Photo</i>
                </a>
              </li>
              <li class="nav-item">
                <!-- Link to Profile Page -->
                <a href="#">
                  <i>Profile</i>
                </a>
              </li>
              <li class="nav-item">
                <!-- Log out -->
                <a href="#">
                  <i>Log out</i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <!-- End Header Section with Navigation Bar -->

    <!-- Starts Main Section -->
    <main>
      <!-- Start Profile Details Section -->
      <div class="profile">
        <!-- Start Profile Personal Data Section -->
        <div class="profile-data">
          <div class="profile_img">
            <div class="image">
              <!-- Profile Image -->
              <img src="/static/images/person.png" alt="img8" />
            </div>
          </div>
          <div class="personal">
            <div class="edit">
              <!-- User Username -->
              <p>d_kalaydzhiev</p>

              <!-- IF the viewer is the owner of the profile -->
              <!-- Link to Edit Profile Page -->
              <a href="#">
                <img
                  class="edit-img"
                  src="/static/images/edit-pen-icon-6.jpg"
                  alt="edit button"
                />
              </a>

              <!-- Link to Delete Profile Page -->
              <a href="">
                <img
                  class="bin-img"
                  src="/static/images/icon-remove-22.jpg"
                  alt="bin button"
                />
              </a>
              <!-- End IF the viewer is the owner of the profile -->
            </div>
            <div class="data">
              <!-- Total Number of Photos by the User -->
              <span>4</span>
              <p>photos</p>

              <!-- Total Number of Pets owned by the User -->
              <span>7</span>
              <p>pets</p>

              <!-- Total Number of Likes for the User -->
              <span>436</span>
              <p>likes</p>
            </div>
            <!-- User First and Last Name IF Added -->
            <h3 class="names">Diyan Kalaydziev</h3>

            <!-- User Email Address -->
            <p class="email">d.denov@gmail.com</p>

            <!-- User Gender IF Added -->
            <p class="gender">Male</p>
          </div>
        </div>
        <!-- End Profile Personal Data Section -->

        <!-- Start Pets Data Section -->
        <div class="pets">
          <div class="statuses">
            <!-- Start 1st Pet Details Page -->
            <!-- Link to First Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <!-- Pet Image -->
                    <img
                      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgoIHq82qLYnvomfz5ZkW5CLQ8VNxCyI-hUw&usqp=CAU"
                      alt="pet img"
                    />
                  </div>
                </div>
                <!-- Pet Name -->
                <p>Sasho</p>
              </div>
            </a>
            <!-- End 1st Pet Details Page -->

            <!-- Start 2nd Pet Details Page -->
            <!-- Link to Second Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <!-- Pet Image -->
                    <img
                      src="https://cdn.pixabay.com/photo/2016/12/13/05/15/puppy-1903313__340.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <!-- Pet Name -->
                <p>Todi</p>
              </div>
            </a>
            <!-- End 2nd Pet Details Page -->

            <!-- Start 3rd Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://images.unsplash.com/photo-1611003228941-98852ba62227?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmFieSUyMGRvZ3xlbnwwfHwwfHw%3D&w=1000&q=80"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Mihail</p>
              </div>
            </a>
            <!-- End 3rd Pet Details Page -->

            <!-- Start 4th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/1200px-Cat03.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Petar</p>
              </div>
            </a>
            <!-- End 4th Pet Details Page -->

            <!-- Start 5th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdKYe00NaD5SQjIMvXYPssq0r1dXJggL3ZIg&usqp=CAU"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Stamat</p>
              </div>
            </a>
            <!-- End 5th Pet Details Page -->

            <!-- Start 6th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://cf.ltkcdn.net/small-pets/images/orig/278587-1600x1066-goldfish-swimming-in-fish-tank.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Toni</p>
              </div>
            </a>
            <!-- End 6th Pet Details Page -->

            <!-- Start 7th Pet Details Page -->
            <!-- Link to Pet Details Page -->
            <a href="#">
              <div class="head-pet">
                <div class="status">
                  <div class="image">
                    <img
                      src="https://i.pinimg.com/736x/01/6f/72/016f72c5812e1b8f71bdbf19d8c7558b.jpg"
                      alt="pet img"
                    />
                  </div>
                </div>
                <p>Daisy</p>
              </div>
            </a>
            <!-- End 7th Pet Details Page -->
          </div>
        </div>
        <!-- End Pets Data Section -->

        <!-- Start Last Uploaded Photos Section -->
        <div class="pet-photos">
          <!-- Link to Last Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://i.natgeofe.com/n/de94c416-6d23-45f5-9708-e8d56289268e/naturepl_01132178.jpg?w=636&h=631"
              alt="pet img"
            />
          </a>

          <!-- Link to Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://cf.ltkcdn.net/small-pets/images/orig/278587-1600x1066-goldfish-swimming-in-fish-tank.jpg"
              alt="pet img"
            />
          </a>

          <!-- Link to Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://thumbs.dreamstime.com/b/small-golden-retriever-puppy-6482030.jpg"
              alt="pet img"
            />
          </a>

          <!-- Link to  Uploaded Pet Photo -->
          <a href="#">
            <!-- Pet Photo -->
            <img
              src="https://i.pinimg.com/originals/4e/55/83/4e5583748bc4000805df50e4ebcafffc.png"
              alt="pet img"
            />
          </a>
        </div>
        <!-- End Last Uploaded Photos Section -->

        <!-- IF NO Posts Show No Post Image -->

        <img
          class="no-posts"
          src="/static/images/no_posts.png"
          alt="no posts"
        />
      </div>

      <!-- End Profile Details Section -->
    </main>
    <!-- End Main Section -->

    <!-- Start Footer Section -->
    <div class="footer">
      <span class="footer-section">
        © 2024 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
      </span>
    </div>
    <!-- End Footer Section -->
  </body>
</html>

templates/accounts/register-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet" href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/static/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">

                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Login Page -->
                        <a href="#">
                            <i>Login</i>
                        </a>
                    </li>
                    <li class="nav-item">

                        <!-- Link to Register Page -->
                        <a href="">
                            <i>Register</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>

    <!-- Start Register Section -->
    <div class="login-register-div">
        <div class="login-register-box">
            <h1>Petstagram</h1>

            <!-- Start Register Form -->
            <form action="">
                <input type="text" placeholder="Username">

                <input type="email" placeholder="Email">

                <input type="password" placeholder="Password">

                <input type="password" placeholder="Repeat Password">

                <!-- Register Button -->
                <button type="submit">Register</button>
            </form>
            <!-- End Register Form -->

        </div>
        <div class="second-option">

            <!-- Link to Login Page -->
            <p>Have an account? <a href="#">Log in</a></p>
        </div>
    </div>
    <!-- End Register Section -->

</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2024 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

templates/photos/photo-add-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet" href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/static/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">
                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <!-- Log out -->
                        <a href="#">
                            <i>Log out</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>
    <!-- Start Add Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Add photo</h2>
        <!-- Start Add Photo Form -->
        <form action="" enctype="multipart/form-data">
            <p>
                <label for="id_photo_file">Photo file:</label>
                <input type="file">
            </p>

            <p>
                <label for="id_description">Description:</label>
                <input type="text">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>
            <!-- Add Photo Button -->
            <button class="add-btn" type="submit">Add Photo</button>
        </form>
        <!-- End Add Photo Form -->
    </div>
    <!-- End Add Photo Section -->
</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2024 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>

templates/photos/photo-edit-page.html
<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <link rel="stylesheet" href="/static/css/styles.css">
    <link rel="icon" type="image/x-icon" href="/static/images/free-30-instagram-stories-icons23_122570.png">
    <title>Petstagram</title>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>

<!-- Starts Header Section with Navigation Bar -->
<header>
    <nav class="navbar">
        <div class="container">
            <div class="logo">
                <!-- Link to Home Page -->
                <a href="#">
                    <img width="50px" src="/static/images/free-30-instagram-stories-icons23_122570.png" alt="img1">
                </a>

                <!-- Link to Home Page -->
                <a class="home" href="#">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">
                        <!-- Link to Add Pet Page -->
                        <a href="#">
                            <i>Add Pet</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Add Photo Page -->
                        <a href="#">
                            <i>Add Photo</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <!-- Link to Profile Page -->
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <!-- Log out -->
                        <a href="#">
                            <i>Log out</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>

    <!-- Starts Edit Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit photo</h2>

        <!-- Starts Edit Photo Form -->
        <form action="">

            <p>
                <label for="id_description">Description:</label>
                <input type="text" value="Sasho is an Axolotl">
            </p>

            <p>
                <label for="id_description">Location:</label>
                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location"
                       value="Bansko, Bulgaria">
            </p>

            <p>
                <label for="pets">Tag Pets:</label>

                <select name="pets" id="id_tagged_pets" multiple>
                    <option selected>Sasho</option>
                    <option>Perry</option>
                    <option>Bucky</option>
                    <option>Steve</option>
                </select>
            </p>

            <!-- Edit Photo Button -->
            <button class="edit-btn" type="submit">Edit Photo</button>
        </form>
        <!-- End Edit Photo Form -->

    </div>
    <!-- End Edit Photo Section -->

</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer">
		<span class="footer-section">
			© 2024 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
		</span>
</div>
<!-- End Footer Section -->

</body>
</html>